---
title: "Practice EXCEL"
output: pdf_document
---

# 1. Data Cleaning

- Go to the official data website of the UNICEF organisation: https://data.unicef.org

- Find the list of dataset and look for "Birth registration data"

- On the "Birth registration data", click on [download spreadsheet](https://data.unicef.org/wp-content/uploads/2019/10/Birth_registration_database_June-2020.xlsx) and save it on your desktop

## Then:

1. Ditch the chart and all non values
2. Columns start at column A
3. Column headings in row 1
4. Save as .csv file

# 2. Data Transformation

- Go to the MT5000 Loop page
- Download and open the document "employee_dd.xls"

## Then:

1. Extension: Create a new variable/column which is the average response to all the questions from the survey for each employee (q1 to q9)

2. Reduction: Filter employee’s 2019 salary to keep only employees with a salary higher than 30k

3. Aggregation: Calculate the average salary by gender and by location

4. Combination: Using the VLOOKUP function, add to the table a column corresponding to the 2017 salary located in the 2nd sheet

To obtain the corrections, email your answers to damien.dupre@dcu.ie.