---
title: "Practice SQL"
output: pdf_document
---

Use the "northwind_onlinedemo.txt" database with https://sqliteonline.com/ as indicated in the tutorial 1 and formulate the SQL queries by yourself to answer the following questions. Don’t hesitate to Google your SQL question to find help. To obtain the corrections, email your answers to damien.dupre@dcu.ie.

Questions:

1. Retrieve all columns in the Region table.

2. Select the FirstName and LastName columns from the Employees table.

3. Select the FirstName and LastName columns from the Employees table. Sort by LastName.

4. Create a report showing Northwind’s orders sorted by Freight from most expensive to cheapest. Show OrderID, OrderDate, ShippedDate, CustomerID, and Freight.

5. Create a report showing the title and the first and last name of all sales representatives.

6. Create a report showing the first and last names of all employees who have a region corresponding to ‘WA’.

7. Create a report showing the first and last name of all employees whose last names start with a letter in the last half of the alphabet. Sort by LastName in descending order.

8. Create a report showing the first and last name of all sales representatives who are from Seattle or Redmond.

9. Create a report that shows the company name, contact title, city and country of all customers in Mexico or in any city in Spain except Madrid.

10. If the cost of freight is greater than or equal to 500.00, it will now be taxed by 10%. Create a report that shows the order id, freight cost, freight cost with this tax for all orders of 500 or more.

11. Find the Total Number of Units Ordered of Product ID 3

12. Retrieve the number of employees in each city

13. Create a report showing employee orders.

14. Create a report showing the Order ID, the name of the company that placed the order, and the first and last name of the associated employee. Only show orders placed after January 1, 1998 that shipped after they were required. Sort by Company Name.

15. Create a report that shows the total quantity of products (from the Order_Details table) ordered. Only show records for products.